name: Terraform Shared Action

on:
  workflow_call:
    inputs:
      terraform_mode:
        default: plan
        description: Mode to invoke Terraform
        type: string

jobs:
  Terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.5

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false -out=./plan.tmp

      - name: Terraform Apply
        if: inputs.terraform_mode == 'apply'
        run: terraform apply -auto-approve ./plan.tmp